#!/usr/bin/env python3
# _*_ coding:utf-8 _*_
# 
# Version: 0.0.1
# Date:2020.02
# Author: yjz
#

import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime 
import sys
#from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


#print('Command has', len(sys.argv), 'arguments.')
#print('Argument list is', str(sys.argv))

if len(sys.argv) < 2:
    print("sys.argv[0] file_name")
    exit

file_name = sys.argv[1]
print(file_name)

#00:00:13.846387 TaskID 0 sendID 0 recvcount 350 walkstate 0 sideState 0 version 10541 McuADv 995 McuADa 34 battery 90
#x,y = np.loadtxt(file_name, delimiter=' ', unpack=True, usecols=[6,14])
TimeArray,battery = np.loadtxt(file_name, delimiter=' ', unpack=True, usecols=[0, 18],dtype=bytes).astype(str)
#recvcount,McuADv,McuADa,battery = np.loadtxt(file_name, delimiter=' ', unpack=True, usecols=[6, 14, 16, 18])
#print(recvcount)
#x=recvcount/50
#ADv=McuADv/10
#print(x)
#print(y)

x = [datetime.strptime(d, '%H:%M:%S.%f').strftime('%H:%M:%S')  for d in TimeArray]

y = [int(i) for i in battery]

plt.figure(figsize=(20, 20))
#plt.axis("equal")
#plt.xlim(0, 1000)
plt.ylim(0, 100)
#plt.plot(x, McuADv, ',', label='power_adv', color='blue')
#plt.plot(x, McuADa, ',', label='power_ada', color='red')
plt.plot(x, y, ',', label='power_battery', color='green')

#plt.plot(x,McuADv,linewidth=0.5) #设置线条宽度
#plt.plot(x,McuADa,linewidth=0.5)
plt.plot(x,y,linewidth=0.5)

#plt.rcParams['font.sans-serif'] = ['SimHei'] #设置中文乱码问题
plt.xlabel('time(s)')
plt.ylabel('power(%)')
plt.title('power_chart')
#plt.title('轨迹')
plt.legend()
plt.gcf().autofmt_xdate() 
plt.gcf().set_size_inches(20,20)
i = int(len(x)/60)
plt.xticks(list(x)[::i], x[::i],rotation=75)
plt.savefig("./output/power.png")
plt.show()

