#!/usr/bin/env python3
# _*_ coding:utf-8 _*_


import matplotlib.pyplot as plt
import numpy as np
import sys
#from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


#print('Command has', len(sys.argv), 'arguments.')
#print('Argument list is', str(sys.argv))

if len(sys.argv) < 2:
    print("sys.argv[0] file_name")
    exit

file_name = sys.argv[1]
print(file_name)

#定义坐标轴
#fig = plt.figure()
ax1 = plt.axes(projection='3d')

x,y,z = np.loadtxt(file_name, delimiter=',', unpack=True, usecols=[1,2,3])
ax1.scatter3D(x,y,z, cmap='Blues')  #绘制散点图
ax1.plot3D(x,y,z,'gray')    #绘制空间曲线
plt.gcf().set_size_inches(20,20)
plt.savefig("./output/trail.png")
plt.show()


