#!/usr/bin/env python3
# _*_ coding:utf-8 _*_
# 
# Version: 0.0.1
# Date:2020.02
# Author: yjz
#

import sys
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches

#print('Command has', len(sys.argv), 'arguments.')
#print('Argument list is', str(sys.argv))

if len(sys.argv) < 2:
    print("sys.argv[0] file_name")
    exit

file_name = sys.argv[1]
#print(file_name)

#将画布分为1*1,并且将画布定位到第一个axis系中
ax = plt.subplot(111)
ax.axis([-20000,20000,-20000,20000])
#ax.axis([-15000,15000,-15000,15000])

file = open(file_name, 'r')
read_all = False
while not read_all:
    line = file.readline()
    if not line:
        read_all = True
        break
    line_elements = line.split(',')
    minx=int(line_elements[0])
    miny=int(line_elements[1])
    maxx=int(line_elements[2])
    maxy=int(line_elements[3])
    #print("minx, miny, maxx, maxy:", minx, miny, maxx, maxy)
    xd=maxx-minx
    yd=maxy-miny
    #print("xd, yd:", xd, yd)
    ax.add_patch(patches.Rectangle((minx, miny), xd, yd))

file.close()

#ax.set_title("区域分割")
ax.set_title("region segmentation")
plt.gcf().set_size_inches(20,20)
plt.savefig("./output/region_segmentation.png")
#plt.show()

